// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_analogs_core
SEXP find_analogs_core(const NumericMatrix& focal_mm, const NumericMatrix& ref_mm, int k, const NumericVector& max_clim, double max_geog, const std::string& geo_mode, int mode_code, int weight_code, double theta);
RcppExport SEXP _analogs_find_analogs_core(SEXP focal_mmSEXP, SEXP ref_mmSEXP, SEXP kSEXP, SEXP max_climSEXP, SEXP max_geogSEXP, SEXP geo_modeSEXP, SEXP mode_codeSEXP, SEXP weight_codeSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type focal_mm(focal_mmSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ref_mm(ref_mmSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type max_clim(max_climSEXP);
    Rcpp::traits::input_parameter< double >::type max_geog(max_geogSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type geo_mode(geo_modeSEXP);
    Rcpp::traits::input_parameter< int >::type mode_code(mode_codeSEXP);
    Rcpp::traits::input_parameter< int >::type weight_code(weight_codeSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(find_analogs_core(focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code, weight_code, theta));
    return rcpp_result_gen;
END_RCPP
}
// analogs_euclid_cpp
double analogs_euclid_cpp(NumericVector a, NumericVector b);
RcppExport SEXP _analogs_analogs_euclid_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(analogs_euclid_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// analogs_haversine_cpp
double analogs_haversine_cpp(NumericVector lonlat_a, NumericVector lonlat_b);
RcppExport SEXP _analogs_analogs_haversine_cpp(SEXP lonlat_aSEXP, SEXP lonlat_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lonlat_a(lonlat_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lonlat_b(lonlat_bSEXP);
    rcpp_result_gen = Rcpp::wrap(analogs_haversine_cpp(lonlat_a, lonlat_b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_analogs_find_analogs_core", (DL_FUNC) &_analogs_find_analogs_core, 9},
    {"_analogs_analogs_euclid_cpp", (DL_FUNC) &_analogs_analogs_euclid_cpp, 2},
    {"_analogs_analogs_haversine_cpp", (DL_FUNC) &_analogs_analogs_haversine_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_analogs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
