// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_analogs_matrix_matrix
DataFrame find_analogs_matrix_matrix(arma::mat focal_coords, arma::mat focal_climate, arma::mat ref_coords, arma::mat ref_climate, Nullable<double> max_dist, Nullable<double> max_clim, std::string weight, std::string fun, Nullable<int> n);
RcppExport SEXP _analogs_find_analogs_matrix_matrix(SEXP focal_coordsSEXP, SEXP focal_climateSEXP, SEXP ref_coordsSEXP, SEXP ref_climateSEXP, SEXP max_distSEXP, SEXP max_climSEXP, SEXP weightSEXP, SEXP funSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type focal_coords(focal_coordsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type focal_climate(focal_climateSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ref_coords(ref_coordsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ref_climate(ref_climateSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type max_clim(max_climSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< std::string >::type fun(funSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(find_analogs_matrix_matrix(focal_coords, focal_climate, ref_coords, ref_climate, max_dist, max_clim, weight, fun, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_analogs_find_analogs_matrix_matrix", (DL_FUNC) &_analogs_find_analogs_matrix_matrix, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_analogs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
