// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_analog_index_cpp
SEXP build_analog_index_cpp(const NumericMatrix& ref_mm, const std::string& coord_type, int index_res);
RcppExport SEXP _analogs_build_analog_index_cpp(SEXP ref_mmSEXP, SEXP coord_typeSEXP, SEXP index_resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ref_mm(ref_mmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type coord_type(coord_typeSEXP);
    Rcpp::traits::input_parameter< int >::type index_res(index_resSEXP);
    rcpp_result_gen = Rcpp::wrap(build_analog_index_cpp(ref_mm, coord_type, index_res));
    return rcpp_result_gen;
END_RCPP
}
// query_analog_index_cpp
SEXP query_analog_index_cpp(SEXP index_list, const NumericMatrix& focal_mm, const NumericMatrix& ref_mm, int k, const NumericVector& max_clim, double max_geog, int mode_code, int weight_code, double theta);
RcppExport SEXP _analogs_query_analog_index_cpp(SEXP index_listSEXP, SEXP focal_mmSEXP, SEXP ref_mmSEXP, SEXP kSEXP, SEXP max_climSEXP, SEXP max_geogSEXP, SEXP mode_codeSEXP, SEXP weight_codeSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type index_list(index_listSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type focal_mm(focal_mmSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ref_mm(ref_mmSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type max_clim(max_climSEXP);
    Rcpp::traits::input_parameter< double >::type max_geog(max_geogSEXP);
    Rcpp::traits::input_parameter< int >::type mode_code(mode_codeSEXP);
    Rcpp::traits::input_parameter< int >::type weight_code(weight_codeSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(query_analog_index_cpp(index_list, focal_mm, ref_mm, k, max_clim, max_geog, mode_code, weight_code, theta));
    return rcpp_result_gen;
END_RCPP
}
// find_analogs_core
SEXP find_analogs_core(const NumericMatrix& focal_mm, const NumericMatrix& ref_mm, int k, const NumericVector& max_clim, double max_geog, const std::string& geo_mode, int mode_code, int weight_code, double theta, int lattice_res);
RcppExport SEXP _analogs_find_analogs_core(SEXP focal_mmSEXP, SEXP ref_mmSEXP, SEXP kSEXP, SEXP max_climSEXP, SEXP max_geogSEXP, SEXP geo_modeSEXP, SEXP mode_codeSEXP, SEXP weight_codeSEXP, SEXP thetaSEXP, SEXP lattice_resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type focal_mm(focal_mmSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ref_mm(ref_mmSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type max_clim(max_climSEXP);
    Rcpp::traits::input_parameter< double >::type max_geog(max_geogSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type geo_mode(geo_modeSEXP);
    Rcpp::traits::input_parameter< int >::type mode_code(mode_codeSEXP);
    Rcpp::traits::input_parameter< int >::type weight_code(weight_codeSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type lattice_res(lattice_resSEXP);
    rcpp_result_gen = Rcpp::wrap(find_analogs_core(focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code, weight_code, theta, lattice_res));
    return rcpp_result_gen;
END_RCPP
}
// profile_find_analogs
Rcpp::List profile_find_analogs(const NumericMatrix& focal_mm, const NumericMatrix& ref_mm, int k, const NumericVector& max_clim, double max_geog, const std::string& geo_mode, int mode_code, int weight_code, double theta, int lattice_res, bool enable_profiling);
RcppExport SEXP _analogs_profile_find_analogs(SEXP focal_mmSEXP, SEXP ref_mmSEXP, SEXP kSEXP, SEXP max_climSEXP, SEXP max_geogSEXP, SEXP geo_modeSEXP, SEXP mode_codeSEXP, SEXP weight_codeSEXP, SEXP thetaSEXP, SEXP lattice_resSEXP, SEXP enable_profilingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type focal_mm(focal_mmSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ref_mm(ref_mmSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type max_clim(max_climSEXP);
    Rcpp::traits::input_parameter< double >::type max_geog(max_geogSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type geo_mode(geo_modeSEXP);
    Rcpp::traits::input_parameter< int >::type mode_code(mode_codeSEXP);
    Rcpp::traits::input_parameter< int >::type weight_code(weight_codeSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type lattice_res(lattice_resSEXP);
    Rcpp::traits::input_parameter< bool >::type enable_profiling(enable_profilingSEXP);
    rcpp_result_gen = Rcpp::wrap(profile_find_analogs(focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code, weight_code, theta, lattice_res, enable_profiling));
    return rcpp_result_gen;
END_RCPP
}
// emit_pairs_cpp
SEXP emit_pairs_cpp(List res, NumericMatrix focal_mm, NumericMatrix ref_mm, bool report_dist, std::string geo_mode);
RcppExport SEXP _analogs_emit_pairs_cpp(SEXP resSEXP, SEXP focal_mmSEXP, SEXP ref_mmSEXP, SEXP report_distSEXP, SEXP geo_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type focal_mm(focal_mmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ref_mm(ref_mmSEXP);
    Rcpp::traits::input_parameter< bool >::type report_dist(report_distSEXP);
    Rcpp::traits::input_parameter< std::string >::type geo_mode(geo_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(emit_pairs_cpp(res, focal_mm, ref_mm, report_dist, geo_mode));
    return rcpp_result_gen;
END_RCPP
}
// analogs_euclid_cpp
double analogs_euclid_cpp(NumericVector a, NumericVector b);
RcppExport SEXP _analogs_analogs_euclid_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(analogs_euclid_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// analogs_haversine_cpp
double analogs_haversine_cpp(NumericVector lonlat_a, NumericVector lonlat_b);
RcppExport SEXP _analogs_analogs_haversine_cpp(SEXP lonlat_aSEXP, SEXP lonlat_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lonlat_a(lonlat_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lonlat_b(lonlat_bSEXP);
    rcpp_result_gen = Rcpp::wrap(analogs_haversine_cpp(lonlat_a, lonlat_b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_analogs_build_analog_index_cpp", (DL_FUNC) &_analogs_build_analog_index_cpp, 3},
    {"_analogs_query_analog_index_cpp", (DL_FUNC) &_analogs_query_analog_index_cpp, 9},
    {"_analogs_find_analogs_core", (DL_FUNC) &_analogs_find_analogs_core, 10},
    {"_analogs_profile_find_analogs", (DL_FUNC) &_analogs_profile_find_analogs, 11},
    {"_analogs_emit_pairs_cpp", (DL_FUNC) &_analogs_emit_pairs_cpp, 5},
    {"_analogs_analogs_euclid_cpp", (DL_FUNC) &_analogs_analogs_euclid_cpp, 2},
    {"_analogs_analogs_haversine_cpp", (DL_FUNC) &_analogs_analogs_haversine_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_analogs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
