# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_analogs_core <- function(focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code, weight_code, theta, lattice_res) {
    .Call(`_analogs_find_analogs_core`, focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code, weight_code, theta, lattice_res)
}

bench_knn_core <- function(focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code) {
    .Call(`_analogs_bench_knn_core`, focal_mm, ref_mm, k, max_clim, max_geog, geo_mode, mode_code)
}

bench_lattice_core <- function(focal_mm, ref_mm, max_clim, max_geog, geo_mode) {
    .Call(`_analogs_bench_lattice_core`, focal_mm, ref_mm, max_clim, max_geog, geo_mode)
}

.emit_pairs_cpp <- function(res, focal_mm, ref_mm, report_dist, geo_mode) {
    .Call(`_analogs_emit_pairs_cpp`, res, focal_mm, ref_mm, report_dist, geo_mode)
}

analogs_euclid_cpp <- function(a, b) {
    .Call(`_analogs_analogs_euclid_cpp`, a, b)
}

analogs_haversine_cpp <- function(lonlat_a, lonlat_b) {
    .Call(`_analogs_analogs_haversine_cpp`, lonlat_a, lonlat_b)
}

