# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_analogs_core <- function(focal_clim_, ref_clim_, focal_geo_, ref_geo_, mode_, k_, climate_band_, radius_km_, geo_flag_, compact_bins_) {
    .Call(`_analogs_find_analogs_core`, focal_clim_, ref_clim_, focal_geo_, ref_geo_, mode_, k_, climate_band_, radius_km_, geo_flag_, compact_bins_)
}

analogs_euclid_cpp <- function(a, b) {
    .Call(`_analogs_analogs_euclid_cpp`, a, b)
}

analogs_haversine_cpp <- function(lonlat_a, lonlat_b) {
    .Call(`_analogs_analogs_haversine_cpp`, lonlat_a, lonlat_b)
}

